export const ACTION_OUTCOME = Object.freeze({
  VALID: 'VALID',
  INVALID_SEQUENCE: 'INVALID_SEQUENCE',
  CRITICAL_FAILURE: 'CRITICAL_FAILURE'
});

export const SCENARIO_STATUS = Object.freeze({
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
});
